w05d04lab/Facebook/config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users, only: [:new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'

end

w05d04lab/Facebook/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, uniqueness: true, presence: true
  validates :password, length: {minimum: 4}
end

w05d04lab/Facebook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

     # Make the current_user method available to views, not just controllers!
    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

end

w05d04lab/Facebook/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end


end

w05d04lab/Facebook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user_id
      flash[:notice] = "You have succesfully signed up!"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

w05d04lab/Facebook/app/helpers/application_helper.rb
module ApplicationHelper
end

w05d04lab/Facebook/app/helpers/sessions_helper.rb
module SessionsHelper
end

w05d04lab/Facebook/app/helpers/users_helper.rb
module UsersHelper
end

w05d04lab/Facebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <% if current_user %>
    Welcome, <%= current_user.name %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to 'Logout', session_path('dummy'), method: :delete %>
  <% else %>
    <%= link_to 'Login', login_path %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to 'Sign Up', new_user_path %>
  <% end %>
</p>
<%= yield %>

</body>
</html>

w05d04lab/Facebook/app/views/users/index.html.erb
<table>
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <% if current_user && current_user.id != user.id %>
        <td><%= link_to "who cares about this dude", user_path(users), method: :delete, data: {confirm: "fasho"} %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

w05d04lab/Facebook/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>