rails_lesson_dtla/coffeeshop/config/routes.rb
Rails.application.routes.draw do
  resources :pastries

  get "beans/" => "beans#index"

  get "beans/new" => "beans#new", as: :new_bean

  post "beans/" => "beans#create"

  get "beans/:id" => "beans#show", as: :bean

  get "beans/:id/edit" => "beans#edit", as: :edit_bean

  patch "beans/:id" => "beans#update"

  delete "beans/:id" => "beans#destroy"

end

rails_lesson_dtla/coffeeshop/app/models/bean.rb
class Bean < ActiveRecord::Base

end

rails_lesson_dtla/coffeeshop/app/models/pastry.rb
class Pastry < ActiveRecord::Base
end

rails_lesson_dtla/coffeeshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_lesson_dtla/coffeeshop/app/controllers/beans_controller.rb
class BeansController < ApplicationController

  def index
    @beans = Bean.all
  end

  def show
    @bean = Bean.find(params[:id])
  end

  def new
    @bean = Bean.new
  end

  def create
    @bean = Bean.new(params.require(:bean).permit(:name, :roast,
                                                  :origin, :quantity))
    if @bean.save
      redirect_to beans_path
    else
      render :new
    end
  end

  def edit
    @bean = Bean.find(params[:id])
  end

  def update
    @bean = Bean.find(params[:id])

    if @bean.update_attributes(params.require(:bean).permit(:name, :roast, :origin, :quantity))
      redirect_to beans_path
    else
      render :edit
    end
  end

  def destroy
    @bean = Bean.find(params[:id])
    @bean.destroy
    redirect_to beans_path
  end

end

rails_lesson_dtla/coffeeshop/app/controllers/pastries_controller.rb
class PastriesController < ApplicationController
  before_action :set_pastry, only: [:show, :edit, :update, :destroy]

  # GET /pastries
  # GET /pastries.json
  def index
    @pastries = Pastry.all
  end

  # GET /pastries/1
  # GET /pastries/1.json
  def show
  end

  # GET /pastries/new
  def new
    @pastry = Pastry.new
  end

  # GET /pastries/1/edit
  def edit
  end

  # POST /pastries
  # POST /pastries.json
  def create
    @pastry = Pastry.new(pastry_params)

    respond_to do |format|
      if @pastry.save
        format.html { redirect_to @pastry, notice: 'Pastry was successfully created.' }
        format.json { render :show, status: :created, location: @pastry }
      else
        format.html { render :new }
        format.json { render json: @pastry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastries/1
  # PATCH/PUT /pastries/1.json
  def update
    respond_to do |format|
      if @pastry.update(pastry_params)
        format.html { redirect_to @pastry, notice: 'Pastry was successfully updated.' }
        format.json { render :show, status: :ok, location: @pastry }
      else
        format.html { render :edit }
        format.json { render json: @pastry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastries/1
  # DELETE /pastries/1.json
  def destroy
    @pastry.destroy
    respond_to do |format|
      format.html { redirect_to pastries_url, notice: 'Pastry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pastry
      @pastry = Pastry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pastry_params
      params.require(:pastry).permit(:name, :flavor, :price)
    end
end

rails_lesson_dtla/coffeeshop/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_lesson_dtla/coffeeshop/app/helpers/beans_helper.rb
module BeansHelper
end

rails_lesson_dtla/coffeeshop/app/helpers/pastries_helper.rb
module PastriesHelper
end

rails_lesson_dtla/coffeeshop/app/views/beans/edit.html.erb
<h1>Switchup</h1>

<%= form_for @bean do |f| %>

  <div class="sub">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="sub">
    <%= f.label :roast %>
    <%= f.text_field :roast %>
  </div>

  <div class="sub">
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>

  <div class="sub">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>


  <%= f.submit "The One You're Looking For" %>

<% end %>

<%= link_to "HeadBack", bean_path %>

rails_lesson_dtla/coffeeshop/app/views/beans/index.html.erb
<h1>Hipster Imported Beans</h1>

<ul class="sub">
 <% @beans.each do |bean| %>
  <li><strong> <%= bean.name %> </strong> - <%= bean.roast %></li>
 <% end %>
</ul>

rails_lesson_dtla/coffeeshop/app/views/beans/new.html.erb
<h1>New Imports</h1>




<%= form_for @bean do |f| %>
<div class="sub">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="sub">
  <%= f.label :roast %>
  <%= f.text_field :roast %>
</div>

<div class="sub">
  <%= f.label :origin %>
  <%= f.text_field :origin %>
</div>

<div class="sub">
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
</div>

<%= f.submit "Add fresh import. Hype" %>

<% end %>

rails_lesson_dtla/coffeeshop/app/views/beans/show.html.erb
<h1 > <%= @bean.name %> </h1>

<p class="sub">This coffee is a <%= @bean.roast %> and it's from <%= @bean.origin %></p>

<%= link_to "Set Phasers to Stun", bean_path, method: :delete,
 data: { confirm: "Are we going in, Captain Kirk?"} %>


<%= link_to "Back to reality, woop there goes Gravity", beans_path, class: "pink" %>

rails_lesson_dtla/coffeeshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeeshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link href='https://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

rails_lesson_dtla/coffeeshop/app/views/pastries/_form.html.erb
<%= form_for(@pastry) do |f| %>
  <% if @pastry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pastry.errors.count, "error") %> prohibited this pastry from being saved:</h2>

      <ul>
      <% @pastry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :flavor %><br>
    <%= f.text_field :flavor %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_lesson_dtla/coffeeshop/app/views/pastries/edit.html.erb
<h1>Editing Pastry</h1>

<%= render 'form' %>

<%= link_to 'Show', @pastry %> |
<%= link_to 'Back', pastries_path %>

rails_lesson_dtla/coffeeshop/app/views/pastries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pastries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Flavor</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pastries.each do |pastry| %>
      <tr>
        <td><%= pastry.name %></td>
        <td><%= pastry.flavor %></td>
        <td><%= pastry.price %></td>
        <td><%= link_to 'Show', pastry %></td>
        <td><%= link_to 'Edit', edit_pastry_path(pastry) %></td>
        <td><%= link_to 'Destroy', pastry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pastry', new_pastry_path %>

rails_lesson_dtla/coffeeshop/app/views/pastries/new.html.erb
<h1>New Pastry</h1>

<%= render 'form' %>

<%= link_to 'Back', pastries_path %>

rails_lesson_dtla/coffeeshop/app/views/pastries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pastry.name %>
</p>

<p>
  <strong>Flavor:</strong>
  <%= @pastry.flavor %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pastry.price %>
</p>

<%= link_to 'Edit', edit_pastry_path(@pastry) %> |
<%= link_to 'Back', pastries_path %>